name: Publish Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          
      - name: Get GPG key
        run: |
          echo "SIGNING_KEY_ID=$(gpg --list-signatures --with-colons | grep 'sig' | head -n 1 | cut -d':' -f5)" >> $GITHUB_ENV
          echo "SIGNING_KEY=$(gpg --armor --export-secret-keys)" >> $GITHUB_ENV
          
      - name: Publish to Maven Central
        run: ./gradlew publish
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}
          SIGNING_KEY_ID: ${{ env.SIGNING_KEY_ID }}
          SIGNING_KEY: ${{ env.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.GPG_PASSPHRASE }} 