name: Publish Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Generate GPG Key
        id: gpg
        run: |
          cat > key-info <<EOF
          %echo Generating a basic OpenPGP key
          Key-Type: RSA
          Key-Length: 2048
          Subkey-Type: RSA
          Subkey-Length: 2048
          Name-Real: Quartel Enterprise
          Name-Email: quare.software@gmail.com
          Expire-Date: 0
          %no-protection
          %commit
          %echo done
          EOF
          
          gpg --batch --gen-key key-info
          KEY_ID=$(gpg --list-signatures --with-colons | grep 'sig' | head -n 1 | cut -d':' -f5)
          echo "key_id=$KEY_ID" >> "$GITHUB_OUTPUT"
          
          # Export the keys
          gpg --armor --export-secret-keys $KEY_ID > private.key
          gpg --armor --export $KEY_ID > public.key
          
      - name: Publish to Maven Central
        run: ./gradlew publish
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}
          SIGNING_KEY_ID: ${{ steps.gpg.outputs.key_id }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ github.workspace }}/private.key 